export const langMap: Record<string, string> = {
  json: "json",
  text: "text",
  markdown: "markdown",
  xml: "xml",
  html: "html",
  javascript: "js",
  node: "js",
  typescript: "ts",
  python: "py",
  java: "java",
  csharp: "cs",
  php: "php",
  ruby: "rb",
  go: "go",
  shell: "sh",
  swift: "swift",
  kotlin: "kt",
  dart: "dart",
  r: "r",
  powershell: "ps1",
  elixir: "el",
};
